Repository CaiJimmy/hugo-theme-stack, pull requests merged in 2020-12, with the labels that each got.

#58 feat(i18n): add Korean translations
  i18n/ko.toml
Labels: enhancement

#57 Add pt-BR.toml
  i18n/pt-BR.toml
Labels: enhancement

#53 feat(sidebar): add support for external avatar
  exampleSite/config.toml
  layouts/partials/sidebar/left.html
Labels: enhancement, major

#64 feat(i18n): add Indonesian translation
  i18n/id.toml
Labels: enhancement

#65 refactor(config): use YAML instead of TOML
  exampleSite/config.toml
  exampleSite/config.yaml
Labels: major, refactor

#68 refactor(i18n): translation key renaming
  i18n/en.toml
  i18n/en.yaml
  i18n/fr.toml
  i18n/fr.yaml
  i18n/id.toml
  i18n/id.yaml
  i18n/ja.toml
  i18n/ja.yaml
  i18n/ko.toml
  i18n/ko.yaml
  i18n/pt-BR.toml
  i18n/pt-BR.yaml
  i18n/zh-CN.toml
  i18n/zh-CN.yaml
  layouts/404.html
  layouts/_default/archives.html
  layouts/page/search.html
  layouts/partials/article/components/footer.html
  layouts/partials/article/components/related-contents.html
  layouts/partials/footer/footer.html
  layouts/partials/widget/archives.html
  layouts/partials/widget/search.html
  layouts/partials/widget/tag-cloud.html
Labels: major, refactor

#73 feat(head): add favicon setting in config.yaml
  exampleSite/config.yaml
  layouts/partials/head/head.html
Labels: enhancement

#74 feat(footer): add copyright since & custom text
  exampleSite/config.yaml
  layouts/index.html
  layouts/partials/footer/footer.html
Labels: enhancement

#76 fix(list): section title style
  layouts/_default/list.html
Labels: bug

#77 refactor(ts): import script using new Hugo Module logic
  assets/jsconfig.json
  assets/ts/main.ts
Labels: major, refactor

#79 refactor(gallery): rewrite gallery
  assets/ts/gallery.ts
  assets/ts/main.ts
  assets/ts/utils.ts
  layouts/_default/_markup/render-image.html
  layouts/partials/article/components/photoswipe.html
Labels: bug, refactor

#75 refactor(article): remove color tag & add custom category color
  assets/ts/main.ts
  exampleSite/content/categories/Test/_index.md
  layouts/partials/article/components/details.html
Labels: feature, refactor

#81 feat(list): add subsection support
  assets/scss/partials/layout/archives.scss
  assets/scss/partials/layout/list.scss
  assets/scss/style.scss
  i18n/en.yaml
  layouts/_default/archives.html
  layouts/_default/list.html
  layouts/_default/term.html
Labels: feature

#82 feat(darkmode): dark mode toggle
  assets/icons/toggle-left.svg
  assets/icons/toggle-right.svg
  assets/scss/partials/highlight/dark.scss
  assets/scss/partials/highlight/light.scss
  assets/scss/partials/menu.scss
  assets/scss/partials/sidebar.scss
  assets/scss/variables.scss
  assets/ts/colorScheme.ts
  assets/ts/main.ts
  exampleSite/config.yaml
  i18n/en.yaml
  i18n/zh-CN.yaml
  layouts/_default/baseof.html
  layouts/partials/footer/components/highlight.html
  layouts/partials/footer/include.html
  layouts/partials/head/colorScheme.html
  layouts/partials/sidebar/left.html
Labels: feature

#83 feat: add option to disable image processing
  exampleSite/config.yaml
  layouts/_default/_markup/render-image.html
  layouts/_default/list.html
  layouts/page/search.json
  layouts/partials/article-list/compact.html
  layouts/partials/article-list/default.html
  layouts/partials/article-list/tile.html
  layouts/partials/article/components/header.html
Labels: feature

#87 fix(list): add missing object-fit property to compact list
  assets/scss/partials/article.scss
Labels: bug

#88 feat(math): add inline math support
  layouts/partials/article/components/math.html
Labels: feature

#89 fix: dark mode toggle inconsistent positioning
  assets/scss/grid.scss
  layouts/_default/baseof.html
Labels: bug, patch

#90 fix(article): twitter_simple shortcode text color
  assets/scss/partials/layout/article.scss
Labels: bug

#93 fix(search): wrong permalink to page
  layouts/page/search.json
Labels: bug, patch

#94 refactor(article): improve category tag style
  assets/scss/partials/article.scss
Labels: refactor

#96 feat(i18n): add Turkish language file
  i18n/tr.yaml
Labels: feature

#97 feat: add bilibili shortcode
  layouts/shortcodes/bilibili.html
Labels: feature

#99 feat(i18n): improve Japanese translation
  i18n/ja.yaml
Labels: feature
