Repository CaiJimmy/hugo-theme-stack, pull requests merged in 2021-08, with the labels that each got.

#292 fix(article): unordered TOC style
  assets/scss/partials/layout/article.scss
Labels: fix

#293 feat(article): add scrollbar to toc
  assets/scss/partials/layout/article.scss
Labels: feature, fix

#261 refactor!: Drop support for non-extended version of Hugo
  resources/_gen/assets/scss/scss/style.scss_b95b077eb505d5c0aff8055eaced30ad.content
  resources/_gen/assets/scss/scss/style.scss_b95b077eb505d5c0aff8055eaced30ad.json
Labels: refactor, major

#294 feat(menu): support open an entry in new tab
  README.md
  exampleSite/config.yaml
  layouts/partials/sidebar/left.html
  netlify.toml
Labels: feature

#295 feat(article): copy button for highlight block
  assets/scss/partials/layout/article.scss
  assets/ts/main.ts
Labels: feature

#297 feat(i18n): add `readingTime` russian translation
  i18n/ru.yaml
Labels: feature

#306 fix(article): change `.article-time` classname to `.article-lastmod`
  assets/scss/partials/layout/article.scss
  layouts/partials/article/components/footer.html
Labels: fix

#304 feat(comments): giscus integration
  exampleSite/config.yaml
  layouts/partials/comments/provider/giscus.html
Labels: feature

#307 feat(comments): DisqusJS integration
  assets/scss/partials/comments/disqusjs.scss
  exampleSite/config.yaml
  layouts/partials/comments/provider/disqusjs.html
Labels: feature

#323 fix(config): doc link
  exampleSite/config.yaml
Labels: fix

#326 refactor(article): better support for svg and external images
  assets/ts/gallery.ts
  layouts/_default/_markup/render-image.html
Labels: refactor, fix

#325 feat(i18n): add PL translation for reading time
  i18n/pl.yaml
Labels: feature
