Repository CaiJimmy/hugo-theme-stack, pull requests merged in 2021-06, with the labels that each got.

#214 feat: Add support for Google Analytics v4
  layouts/partials/head/head.html
Labels: feature

#211 feat: change horizontal scrollbar styles
  assets/scss/partials/layout/list.scss
  assets/scss/variables.scss
Labels: feature, minor

#231 refactor: rewrite grid system & style changes
  assets/scss/breakpoints.scss
  assets/scss/grid.scss
  assets/scss/partials/article.scss
  assets/scss/partials/layout/article.scss
  assets/scss/partials/menu.scss
  assets/scss/partials/sidebar.scss
  assets/scss/variables.scss
  layouts/_default/single.html
  layouts/post/single.html
Labels: refactor

#227 feat: change the page vertical scrollbar styles
  assets/scss/partials/base.scss
  assets/scss/partials/layout/list.scss
  assets/scss/variables.scss
  assets/ts/colorScheme.ts
  layouts/partials/comments/provider/remark42.html
  layouts/partials/comments/provider/utterances.html
  layouts/partials/comments/provider/waline.html
  layouts/partials/head/colorScheme.html
Labels: feature

#232 feat: Table of Contents
  README.md
  assets/scss/grid.scss
  assets/scss/partials/base.scss
  assets/scss/partials/layout/article.scss
  assets/scss/partials/sidebar.scss
  exampleSite/config.yaml
  i18n/en.yaml
  layouts/_default/baseof.html
  layouts/_default/single.html
  layouts/post/single.html
Labels: feature

#237 feat(i18n): add Japanese translation of Table of Content
  i18n/ja.yaml
Labels: feature
