Repository CaiJimmy/hugo-theme-stack, pull requests merged in 2022-01, with the labels that each got.

#447 refactor(search): avoid issue with one character keyword
  assets/jsconfig.json
  assets/ts/search.tsx
Labels: refactor

#455 fix(shortcode): conflict with gist shortcode
  assets/ts/main.ts
Labels: fix

#464 feat(comment): update twikoo version to 1.4.15
  layouts/partials/comments/provider/twikoo.html
Labels: feature

#461 feat: add custom.ts
  layouts/partials/footer/components/script.html
Labels: feature

#460 feat: turn stack theme into a hugo module
  README.md
  go.mod
Labels: feature

#425 feat(article): Scrollspy for the table of contents
  .gitignore
  assets/scss/partials/base.scss
  assets/scss/partials/layout/article.scss
  assets/ts/main.ts
  assets/ts/scrollspy.ts
  assets/ts/smoothAnchors.ts
Labels: feature

#298 feat(comments): add https://cactus.chat support
  data/external.yaml
  exampleSite/config.yaml
  layouts/partials/comments/provider/cactus.html
Labels: feature
