Repository CaiJimmy/hugo-theme-stack, pull requests merged in 2022-03, with the labels that each got.

#520 refactor: Use flexbox gap
  assets/scss/grid.scss
  assets/scss/partials/article.scss
  assets/scss/partials/footer.scss
  assets/scss/partials/layout/archives.scss
  assets/scss/partials/layout/article.scss
  assets/scss/partials/layout/list.scss
  assets/scss/partials/layout/search.scss
  assets/scss/partials/menu.scss
  assets/scss/partials/pagination.scss
  assets/scss/partials/sidebar.scss
  assets/scss/partials/widgets.scss
  assets/scss/style.scss
  assets/scss/variables.scss
  layouts/_default/archives.html
  layouts/_default/list.html
  layouts/page/search.html
  layouts/partials/article/components/related-contents.html
  layouts/partials/sidebar/left.html
Labels: refactor

#519 feat: add RTL Support and update demo site to Show Arabic/RTL content
  assets/scss/partials/base.scss
  assets/scss/partials/layout/article.scss
  assets/scss/partials/layout/search.scss
  exampleSite/config.yaml
  exampleSite/content/post/placeholder-text/index.ar.md
  layouts/_default/baseof.html
Labels: feature

#157 feat(i18n): add Arabic translation
  i18n/ar.yaml
Labels: feature

#524 feat: new left sidebar layout
  assets/scss/partials/menu.scss
  assets/scss/partials/sidebar.scss
  config.yaml
  layouts/partials/sidebar/left.html
Labels: feature

#525 fix: disable external image lightbox
  assets/ts/gallery.ts
Labels: fix

#534 feat: same container width on all pages
  layouts/_default/baseof.html
Labels: feature

#538 feat(i18n): add missing ja & zh-CN translations
  i18n/ja.yaml
  i18n/zh-CN.yaml
Labels: feature
